[manager]

# Selecionar tudo
[[manager.keymap]]
on   = "<C-a>"
run  = "toggle_all --state=on"
desc = "Selecionar tudo"

# Copiar
[[manager.keymap]]
on   = "<C-c>"
run  = "yank"
desc = "Copiar arquivos selecionados"

# Cortar
[[manager.keymap]]
on   = "<C-x>"
run  = "yank --cut"
desc = "Cortar arquivos selecionados"

# Colar
[[manager.keymap]]
on   = "<C-v>"
run  = "paste"
desc = "Colar arquivos"

# Cancelar corte/cópia
[[manager.keymap]]
on   = "<C-S-x>"
run  = "unyank"
desc = "Cancelar corte/cópia"

# Abrir arquivo/diretório
[[manager.keymap]]
on   = "<Enter>"
run  = "open"
desc = "Abrir arquivo/diretório"

# Excluir arquivo (mandar para lixeira)
[[manager.keymap]]
on   = "<Delete>"
run  = "remove"
desc = "Excluir arquivos selecionados"

# Movimento
[[manager.keymap]]
on   = "<Up>"
run  = "arrow -1"
desc = "Mover cursor para cima"

[[manager.keymap]]
on   = "<Down>"
run  = "arrow 1"
desc = "Mover cursor para baixo"

[[manager.keymap]]
on   = "<Left>"
run  = "leave"
desc = "Voltar diretório"

[[manager.keymap]]
on   = "<Right>"
run  = "enter"
desc = "Entrar no diretório"

# --- Editor ---
[[mgr.prepend_keymap]]
on   = "<C-e>"
run  = "exec code"
desc = "Open VSCode in current folder"

# --- Git files plugin ---
[[mgr.prepend_keymap]]
on   = "<C-g>"
run  = "plugin vcs-files"
desc = "Show Git file changes"

# --- Chmod plugin ---
[[mgr.prepend_keymap]]
on   = "<C-p>"
run  = "plugin chmod"
desc = "Chmod on selected files"
